version: '3.8'

services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    volumes:
      - isponsorblocktv_data:/app/data

volumes:
  isponsorblocktv_data:
    external: true
