version: '3.8'

services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
